# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d99b3dab690804c499c98e2bee9843e2a525ae392e55f806b38c8158dd12152698474e48f4b1d76d279a2563f3f71be6c0e5bf3b076dd2fb771fa30f1b686c0

test:
  secret_key_base: 3689895c19577522882292ee5ad05b6e6c6678aabb7a998b8cb042b2cc335f048735291724a8a8110f9b54e5a937a7e283ff1b2cdc64774ff9054cbee6e40449

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
